### ISSUE TITLE
Implement global/default config

### ISSUE THREAD

**Issue by toddnestor** [kernow/shortcode#46]
With changing this gem to have separate instances, it'd be good to be able to add some default configuration options (default shortcodes, templates, etc).

I had originally called this a "global configuration" but I think @kernow's suggestion of calling it the "default configuration" probably makes more sense.

I can handle building this, let's just agree on the terminology first.

**Comment by kernow** [comment]
My preference is for "default" as it implies a default will be used unless it is overwritten. I'm happy for you to go ahead unless anyone comes in with another opinion.

**Comment by toddnestor** [comment]
I think I'll go ahead and do this PR tonight/tomorrow morning.

When are you thinking of doing the 2.0 release of the gem?

**Comment by kernow** [comment]
@toddnestor I'm going to add some deprecation warnings around the singleton usage and do another 1.x release and leave that for a while so that people can update their code. Then I will do a 2.0 release which removes singleton usage.

Any new features can be released in a 1.x release, only breaking changes require a major version bump.
